# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:05:09+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional, Union
from uuid import UUID

from pydantic import BaseModel, EmailStr, Field, RootModel, conint, constr


class APIKey(BaseModel):
    client_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    comment: Optional[str] = Field(
        None, examples=['API key used for Splunk integration']
    )
    counter: Optional[int] = Field(None, examples=[1])
    created_at: Optional[int] = Field(None, examples=[1576300370])
    created_by: Optional[EmailStr] = Field(None, examples=['user@example.com'])
    id: UUID = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    inactive: Optional[bool] = Field(None, examples=['tue'])
    last_used_at: Optional[int] = Field(None, examples=[0])
    last_used_ip: Optional[str] = Field(None, examples=['127.0.0.1'])
    last_used_ua: Optional[str] = Field(None, examples=['curl/7.44.1'])
    organization_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    token: Optional[str] = Field(None, examples=['CTXXXXXXXXXXXXX'])
    type: Optional[str] = Field(None, examples=['org'])
    usage_limit: Optional[int] = Field(None, examples=[10000])
    usage_today: Optional[int] = Field(None, examples=[100])


class APIKeyOptions(BaseModel):
    comment: Optional[str] = Field(None, examples=['Splunk integration key'])
    organization_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )


class AWSCredentialFields(BaseModel):
    access_key: str = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    regions: Optional[str] = Field(None, examples=['us-west-1, us-east-2'])
    role: Optional[str] = Field(None, examples=['rumble-role'])
    secret_access_key: str = Field(
        ..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    use_cross_account_org: Optional[str] = Field(None, examples=['true'])


class Agent(BaseModel):
    arch: Optional[str] = Field(None, examples=['amd64'])
    client_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    connected: Optional[bool] = Field(None, examples=[True])
    created_at: Optional[int] = Field(None, examples=[1576300370])
    deactivated_at: Optional[int] = Field(None, examples=[0])
    external_ip: Optional[str] = Field(None, examples=['1.1.1.1'])
    host_id: Optional[str] = Field(None, examples=['6f9e6fe52271da70962e007183c5c9c9'])
    hub_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    id: UUID = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    inactive: Optional[bool] = Field(None, examples=[False])
    internal_ip: Optional[str] = Field(None, examples=['192.168.0.1'])
    last_checkin: Optional[int] = Field(None, examples=[1576300370])
    name: Optional[
        constr(
            pattern=r'^(([a-zA-Z0-9]|[a-zA-Z0-9][a-zA-Z0-9\-]{0,61}[a-zA-Z0-9])\.)*([A-Za-z0-9]|[A-Za-z0-9][A-Za-z0-9\-]{0,61}[A-Za-z0-9])$'
        )
    ] = Field(None, examples=['RUMBLE-AGENT'])
    organization_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    os: Optional[str] = Field(None, examples=['Windows'])
    site_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    system_info: Optional[Dict[str, Any]] = None
    updated_at: Optional[int] = Field(None, examples=[1576300370])
    version: Optional[str] = Field(
        None,
        examples=[
            '1.2.3 (build 20191219224016) [fc50c5eefdc3ff5c60533c3c345d14d336396272]'
        ],
    )


class AgentSiteID(BaseModel):
    site_id: UUID = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])


class Asset(BaseModel):
    addresses: Optional[List[str]] = None
    addresses_extra: Optional[List[str]] = None
    agent_name: Optional[str] = Field(None, examples=['LAPTOP-F4P1R6'])
    alive: Optional[bool] = Field(None, examples=[True])
    attributes: Optional[Dict[str, str]] = None
    comments: Optional[str] = Field(None, examples=['File Server'])
    created_at: Optional[int] = Field(None, examples=[1576300370])
    credentials: Optional[Dict[str, str]] = None
    detected_by: Optional[str] = Field(None, examples=['icmp'])
    domains: Optional[List[str]] = None
    first_seen: Optional[int] = Field(None, examples=[1576300370])
    hw: Optional[str] = Field(None, examples=['Dell PowerEdge 2500'])
    id: UUID = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    last_agent_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    last_seen: Optional[int] = Field(None, examples=[1576300370])
    last_task_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    lowest_rtt: Optional[int] = Field(None, examples=[1])
    lowest_ttl: Optional[int] = Field(None, examples=[0])
    mac_vendors: Optional[List[str]] = None
    macs: Optional[List[str]] = None
    names: Optional[List[str]] = None
    newest_mac: Optional[str] = Field(None, examples=['11:22:33:44:55:66'])
    newest_mac_age: Optional[int] = Field(None, examples=[1304035200000000000])
    newest_mac_vendor: Optional[str] = Field(None, examples=['Intel Corporate'])
    org_name: Optional[str] = Field(None, examples=['Test Labs'])
    organization_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    os: Optional[str] = Field(None, examples=['Ubuntu Linux'])
    os_version: Optional[str] = Field(None, examples=[18.04])
    rtts: Optional[Dict[str, Any]] = None
    service_count: Optional[int] = Field(None, examples=[10])
    service_count_arp: Optional[int] = Field(None, examples=[1])
    service_count_icmp: Optional[int] = Field(None, examples=[1])
    service_count_tcp: Optional[int] = Field(None, examples=[7])
    service_count_udp: Optional[int] = Field(None, examples=[1])
    service_ports_products: Optional[List[str]] = None
    service_ports_protocols: Optional[List[str]] = None
    service_ports_tcp: Optional[List[str]] = None
    service_ports_udp: Optional[List[str]] = None
    services: Optional[Dict[str, Dict[str, str]]] = None
    site_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    site_name: Optional[str] = Field(None, examples=['Primary'])
    tags: Optional[Dict[str, str]] = None
    type: Optional[str] = Field(None, examples=['Server'])
    updated_at: Optional[int] = Field(None, examples=[1576300370])


class AssetComments(BaseModel):
    comments: str = Field(..., examples=['Sales Laptop'])


class AssetServiceNow(BaseModel):
    addresses_extra: Optional[str] = Field(None, examples=['192.168.0.5;192.168.0.3'])
    addresses_scope: Optional[str] = Field(
        None, examples=['192.168.100.1;192.168.100.2']
    )
    alive: Optional[bool] = Field(None, examples=[True])
    asset_id: UUID = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    comments: Optional[str] = Field(None, examples=['File Server'])
    detected_by: Optional[str] = Field(None, examples=['icmp'])
    domains: Optional[str] = Field(None, examples=['rumble.run;rumble.local.lan'])
    first_discovered: Optional[str] = Field(None, examples=['2006-01-02 15:04:05'])
    hw_product: Optional[str] = Field(None, examples=['PowerEdge'])
    hw_vendor: Optional[str] = Field(None, examples=['Dell'])
    hw_version: Optional[str] = Field(None, examples=[2])
    ip_address: Optional[str] = Field(None, examples=['192.168.0.1'])
    last_discovered: Optional[str] = Field(None, examples=['2006-01-02 15:04:05'])
    last_updated: Optional[str] = Field(None, examples=['2006-01-02 15:04:05'])
    lowest_rtt: Optional[int] = Field(None, examples=[1])
    lowest_ttl: Optional[int] = Field(None, examples=[0])
    mac_address: Optional[str] = Field(None, examples=['11:22:33:44:55:66'])
    mac_manufacturer: Optional[str] = Field(None, examples=['Dell'])
    mac_vendors: Optional[str] = Field(None, examples=['Dell'])
    macs: Optional[str] = Field(None, examples=['11:22:33:44:55:66'])
    name: Optional[str] = Field(None, examples=['www;server'])
    newest_mac_age: Optional[str] = Field(None, examples=['2020-01-01'])
    organization: Optional[str] = Field(None, examples=['Headquarters'])
    os_product: Optional[str] = Field(None, examples=['Windows 10'])
    os_vendor: Optional[str] = Field(None, examples=['Microsoft'])
    os_version: Optional[str] = Field(None, examples=[1903])
    service_count: Optional[int] = Field(None, examples=[10])
    service_count_arp: Optional[int] = Field(None, examples=[1])
    service_count_icmp: Optional[int] = Field(None, examples=[1])
    service_count_tcp: Optional[int] = Field(None, examples=[7])
    service_count_udp: Optional[int] = Field(None, examples=[1])
    site: Optional[str] = Field(None, examples=['Primary'])
    sys_class_name: Optional[str] = Field(None, examples=['cmdb_ci_iot'])
    tags: Optional[str] = Field(None, examples=['owner=IT;location=Austin'])
    type: Optional[str] = Field(None, examples=['Server'])


class AssetTags(BaseModel):
    tags: str = Field(..., examples=['ThisTag=Value -OldTag'])


class AssetTagsWithSearch(BaseModel):
    search: str = Field(..., examples=['alive:true and os:windows'])
    tags: str = Field(..., examples=['ThisTag=Value -OldTag'])


class AssetsWithCheckpoint(BaseModel):
    assets: List[Asset]
    since: int = Field(..., examples=[1576300370])


class AzureClientSecretCredentialFields(BaseModel):
    client_id: str = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    client_secret: str = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    multi_subscription: Optional[str] = Field(None, examples=['true'])
    subscription_id: Optional[str] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    tenant_id: str = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])


class AzureUsernamePasswordCredentialFields(BaseModel):
    client_id: str = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    password: str = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    tenant_id: str = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    username: str = Field(..., examples=['user@example.com'])


class CensysCredentialFields(BaseModel):
    api_url: Optional[str] = Field(None, examples=['https://search.censys.io'])
    client_id: str = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    client_secret: str = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])


class ComponentVersion(BaseModel):
    id: str = Field(..., examples=['agent'])
    version: str = Field(..., examples=['1.0.0'])


class Type(Enum):
    miradore_api_key_v1 = 'miradore_api_key_v1'
    aws_access_secret = 'aws_access_secret'
    crowdstrike_api_key = 'crowdstrike_api_key'
    azure_client_secret = 'azure_client_secret'
    azure_username_password = 'azure_username_password'
    censys_search_api_key = 'censys_search_api_key'
    snmpv2_community = 'snmpv2_community'
    snmpv3_credential = 'snmpv3_credential'
    vmware_username_password = 'vmware_username_password'


class Credential(BaseModel):
    acl: Optional[Dict[str, Any]] = Field(
        None, examples=[{'e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8': 'user'}]
    )
    cidrs: Optional[List[str]] = Field(
        None, examples=[['10.0.0.47/32', '192.168.1.0/24']]
    )
    client_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    created_at: Optional[int] = Field(None, examples=[1576300370])
    created_by_email: Optional[EmailStr] = Field(None, examples=['user@example.com'])
    created_by_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    global_: Optional[bool] = Field(None, alias='global', examples=[False])
    id: UUID = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    last_used_at: Optional[int] = Field(None, examples=[1576300370])
    last_used_by_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    name: Optional[str] = Field(None, examples=['credentials_name'])
    type: Optional[Type] = Field(
        None, description='The service the credentials are for.'
    )


class Type1(Enum):
    miradore_api_key_v1 = 'miradore_api_key_v1'
    aws_access_secret = 'aws_access_secret'


class CrowdstrikeCredentialFields(BaseModel):
    api_url: str = Field(..., examples=['example.crowdstrike.com'])
    client_id: str = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    client_secret: str = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])


class Event(BaseModel):
    action: Optional[str] = Field(None, examples=['login'])
    client_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    created_at: Optional[int] = Field(None, examples=[1576300370])
    details: Optional[Dict[str, Any]] = None
    id: Optional[UUID] = Field(None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    organization_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    processed_at: Optional[int] = Field(None, examples=[0])
    processor_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    site_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    source_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    source_name: Optional[str] = Field(None, examples=['SiteName'])
    source_type: Optional[str] = Field(None, examples=['api'])
    state: Optional[str] = Field(None, examples=['SiteName'])
    success: Optional[bool] = Field(None, examples=[True])
    target_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    target_name: Optional[str] = Field(None, examples=['SiteName'])
    target_type: Optional[str] = Field(None, examples=['api'])


class Group(BaseModel):
    created_at: Optional[int] = Field(None, examples=[1576300370])
    created_by_email: Optional[str] = Field(None, examples=['jsmith@example.com'])
    description: Optional[str] = Field(None, examples=['Viewers Group'])
    expires_at: Optional[int] = Field(None, examples=[1576300370])
    id: UUID = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    name: Optional[str] = Field(None, examples=['Viewers'])
    org_default_role: Optional[str] = Field(None, examples=['admin'])
    org_roles: Optional[Dict[str, Any]] = None
    role_summary: Optional[str] = Field(None, examples=['all:viewer'])
    updated_at: Optional[int] = Field(None, examples=[1576300370])
    user_count: Optional[int] = Field(None, examples=[2])


class GroupMapping(BaseModel):
    created_at: Optional[int] = Field(None, examples=[1576300370])
    created_by_email: Optional[str] = Field(None, examples=['jsmith@example.com'])
    description: Optional[str] = Field(
        None, examples=['Maps basic-attribute to Viewers Group']
    )
    group_id: UUID = Field(..., examples=['2b096711-4d28-4417-8635-64af4f62c1ae'])
    group_name: Optional[str] = Field(None, examples=['Viewers Group'])
    id: UUID = Field(..., examples=['f6cfb91a-52ea-4a86-bf9a-5a891a26f52b'])
    sso_attribute: str = Field(..., examples=['basic-attribute'])
    sso_value: str = Field(..., examples=['basic-attribute-value'])
    updated_at: Optional[int] = Field(None, examples=[1576300370])


class GroupPost(BaseModel):
    description: Optional[str] = Field(None, examples=['Viewers Group'])
    expires_at: Optional[int] = Field(None, examples=[1576300370])
    name: Optional[str] = Field(None, examples=['Viewers'])
    org_default_role: Optional[str] = Field(None, examples=['admin'])
    org_roles: Optional[Dict[str, Any]] = Field(
        None,
        examples=[
            {
                '1a5e612e-4d64-45fe-aa3e-afba5cf3b9bf': 'viewer',
                'fd6d6662-732b-4c4b-8331-051178994384': 'admin',
            }
        ],
    )


class GroupPut(BaseModel):
    description: Optional[str] = Field(None, examples=['Viewers Group'])
    expires_at: Optional[int] = Field(None, examples=[1576300370])
    id: Optional[UUID] = Field(None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    name: Optional[str] = Field(None, examples=['Viewers'])
    org_default_role: Optional[str] = Field(None, examples=['admin'])
    org_roles: Optional[Dict[str, Any]] = Field(
        None,
        examples=[
            {
                '1a5e612e-4d64-45fe-aa3e-afba5cf3b9bf': 'viewer',
                'fd6d6662-732b-4c4b-8331-051178994384': 'admin',
            }
        ],
    )


class License(BaseModel):
    activated_at: Optional[int] = Field(None, examples=[1576300370])
    address_city: Optional[str] = Field(None, examples=['Austin'])
    address_country: Optional[str] = Field(None, examples=['US'])
    address_postal: Optional[str] = Field(None, examples=[78700])
    address_region: Optional[str] = Field(None, examples=['Texas'])
    address_street: Optional[str] = Field(None, examples=['1111 Main St'])
    created_at: Optional[int] = Field(None, examples=[1576300370])
    id: Optional[UUID] = Field(None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    license_expiration: Optional[int] = Field(None, examples=[1576300370])
    license_live_asset_count: Optional[int] = Field(None, examples=[1000])
    license_max_assets: Optional[int] = Field(None, examples=[1000000])
    license_project_asset_count: Optional[int] = Field(None, examples=[5000])
    license_type: Optional[str] = Field(None, examples=['platform'])
    name: Optional[str] = Field(None, examples=['My Company'])
    partner: Optional[str] = Field(None, examples=['Rumble'])
    phone: Optional[str] = Field(None, examples=['512-555-5555'])
    settings: Optional[Dict[str, Any]] = None
    sso_default_role: Optional[str] = Field(None, examples=['viewer'])
    sso_domain: Optional[str] = Field(None, examples=['rumble.run'])
    sso_login_issuer_url: Optional[str] = Field(
        None, examples=['https://accounts.google.com/o/saml2?idpid=issuer']
    )
    sso_login_login_url: Optional[str] = Field(
        None, examples=['https://accounts.google.com/o/saml2?idpid=login']
    )
    sso_login_logout_url: Optional[str] = Field(
        None, examples=['https://accounts.google.com/o/saml2?idpid=logout']
    )
    sso_login_message: Optional[str] = Field(None, examples=['Hello'])
    sso_mode: Optional[str] = Field(None, examples=['required'])
    sso_type: Optional[str] = Field(None, examples=['saml20'])
    subscription_cancel_at: Optional[int] = Field(None, examples=[1576300370])
    subscription_canceled_at: Optional[int] = Field(None, examples=[1576300370])
    subscription_period_end: Optional[int] = Field(None, examples=[1576300370])
    subscription_period_start: Optional[int] = Field(None, examples=[1576300370])
    updated_at: Optional[int] = Field(None, examples=[1576300370])
    via_reseller: Optional[bool] = Field(None, examples=[False])


class MiradoreCredentialFields(BaseModel):
    api_key: str = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    hostname: str = Field(..., examples=['yourcompanyinc.online.miradore.com'])


class OrgOptions(BaseModel):
    description: Optional[str] = Field(None, examples=['Wobbly Widgets, Inc.'])
    expiration_assets_offline: Optional[str] = Field(None, examples=['365'])
    expiration_assets_stale: Optional[str] = Field(None, examples=['365'])
    expiration_scans: Optional[str] = Field(None, examples=['365'])
    export_token: Optional[str] = Field(None, examples=['ETXXXXXXXXXXXXXXXX'])
    name: Optional[str] = Field(None, examples=['My Organization'])
    parent_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    project: Optional[str] = Field(None, examples=[False])


class Organization(BaseModel):
    asset_count: Optional[int] = Field(None, examples=[100])
    client_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    created_at: Optional[int] = Field(None, examples=[1576300370])
    deactivated_at: Optional[int] = Field(None, examples=[0])
    description: Optional[str] = Field(
        None, examples=['All subdivisions of my company']
    )
    download_token: Optional[str] = Field(
        None, examples=['DT11226D9EEEA2B035D42569585900']
    )
    download_token_created_at: Optional[int] = Field(None, examples=[1576300370])
    expiration_assets_offline: Optional[int] = Field(None, examples=[365])
    expiration_assets_stale: Optional[int] = Field(None, examples=[365])
    expiration_scans: Optional[int] = Field(None, examples=[365])
    export_token: Optional[str] = Field(
        None, examples=['ET11226D9EEEA2B035D42569585900']
    )
    export_token_counter: Optional[int] = Field(None, examples=[0])
    export_token_created_at: Optional[int] = Field(None, examples=[1576300370])
    export_token_last_used_at: Optional[int] = Field(None, examples=[0])
    export_token_last_used_by: Optional[str] = Field(None, examples=['127.0.0.1'])
    id: UUID = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    inactive: Optional[bool] = Field(None, examples=[False])
    name: str = Field(..., examples=['My Company'])
    parent_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    permanent: Optional[bool] = Field(None, examples=[True])
    project: Optional[bool] = Field(None, examples=[False])
    service_count: Optional[int] = Field(None, examples=[10])
    service_count_arp: Optional[int] = Field(None, examples=[1])
    service_count_icmp: Optional[int] = Field(None, examples=[1])
    service_count_tcp: Optional[int] = Field(None, examples=[7])
    service_count_udp: Optional[int] = Field(None, examples=[1])
    updated_at: Optional[int] = Field(None, examples=[1576300370])


class SNMPv2CommunitiesCredentialFields(BaseModel):
    community: str = Field(..., examples=['public,private'])


class SNMPv3CredentialFields(BaseModel):
    auth_passphrase: Optional[str] = Field(
        None, alias='auth-passphrase', examples=['authpass']
    )
    auth_protocol: Optional[str] = Field(None, alias='auth-protocol', examples=['sha'])
    context: Optional[str] = Field(None, examples=['vlan-32'])
    privacy_passphrase: Optional[str] = Field(
        None, alias='privacy-passphrase', examples=['privpass']
    )
    privacy_protocol: Optional[str] = Field(
        None, alias='privacy-protocol', examples=['aes']
    )
    username: str = Field(..., examples=['user'])


class ScanFrequency(Enum):
    once = 'once'
    hourly = 'hourly'
    daily = 'daily'
    weekly = 'weekly'
    monthly = 'monthly'
    continuous = 'continuous'


class ScanOptions(BaseModel):
    agent: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    excludes: Optional[str] = None
    host_ping: Optional[str] = Field(None, alias='host-ping', examples=['false'])
    max_attempts: Optional[str] = Field(None, alias='max-attempts', examples=['3'])
    max_group_size: Optional[str] = Field(
        None, alias='max-group-size', examples=['4096']
    )
    max_host_rate: Optional[str] = Field(None, alias='max-host-rate', examples=['100'])
    max_sockets: Optional[str] = Field(None, alias='max-sockets', examples=['500'])
    max_ttl: Optional[str] = Field(None, alias='max-ttl', examples=['255'])
    nameservers: Optional[str] = Field(None, examples=['8.8.8.8'])
    passes: Optional[str] = Field(None, examples=['3'])
    probes: Optional[str] = Field(
        None,
        description='Optional probe list, otherwise all probes are used',
        examples=[
            'arp,bacnet,connect,dns,echo,ike,ipmi,mdns,memcache,mssql,natpmp,netbios,pca,rdns,rpcbind,sip,snmp,ssdp,syn,ubnt,wlan-list,wsd'
        ],
    )
    rate: Optional[str] = Field(None, examples=['10000'])
    scan_description: Optional[str] = Field(
        None, alias='scan-description', examples=['Scan of Wireless']
    )
    scan_frequency: Optional[ScanFrequency] = Field(None, alias='scan-frequency')
    scan_grace_period: Optional[str] = Field(
        None, alias='scan-grace-period', examples=['4']
    )
    scan_name: Optional[str] = Field(None, alias='scan-name', examples=['My Scan'])
    scan_start: Optional[str] = Field(None, alias='scan-start', examples=['0'])
    scan_tags: Optional[str] = Field(
        None, alias='scan-tags', examples=['owner=IT location=Texas']
    )
    screenshots: Optional[str] = Field(None, examples=['true'])
    subnet_ping: Optional[str] = Field(None, alias='subnet-ping', examples=['true'])
    subnet_ping_net_size: Optional[str] = Field(
        None, alias='subnet-ping-net-size', examples=['256']
    )
    subnet_ping_sample_rate: Optional[str] = Field(
        None, alias='subnet-ping-sample-rate', examples=['3']
    )
    targets: str = Field(..., examples=['defaults'])
    tcp_excludes: Optional[str] = Field(None, alias='tcp-excludes', examples=['9500'])
    tcp_ports: Optional[str] = Field(
        None, alias='tcp-ports', examples=['1-1000,5000-6000']
    )


class ScanTemplate(BaseModel):
    acl: Dict[str, Any] = Field(
        ..., examples=[{'e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8': 'user'}]
    )
    agent_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    client_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    created_at: Optional[int] = Field(None, examples=[1576300370])
    created_by: Optional[EmailStr] = Field(None, examples=['user@example.com'])
    created_by_user_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    cruncher_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    description: Optional[str] = Field(None, examples=['My Scan Template'])
    error: Optional[str] = Field(None, examples=['agent unavailable'])
    global_: bool = Field(..., alias='global', examples=[False])
    grace_period: Optional[str] = Field(None, examples=['4'])
    hidden: Optional[bool] = Field(None, examples=[False])
    hosted_zone_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    id: UUID = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    linked_task_count: Optional[int] = Field(None, examples=[1])
    name: Optional[str] = Field(None, examples=['My Scan Template'])
    organization_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    params: Optional[Dict[str, str]] = None
    parent_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    recur: Optional[bool] = Field(None, examples=[False])
    recur_frequency: Optional[str] = Field(None, examples=['hour'])
    recur_last: Optional[int] = Field(None, examples=[1576300370])
    recur_last_task_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    recur_next: Optional[int] = Field(None, examples=[1576300370])
    site_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    size_data: Optional[int] = Field(None, examples=[0])
    size_results: Optional[int] = Field(None, examples=[0])
    size_site: Optional[int] = Field(None, examples=[0])
    source_id: Optional[str] = Field(None, examples=['1'])
    start_time: Optional[int] = Field(None, examples=[1576300370])
    stats: Optional[Dict[str, Any]] = None
    status: Optional[str] = Field(None, examples=['processed'])
    template_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    type: Optional[str] = Field(None, examples=['scan'])
    updated_at: Optional[int] = Field(None, examples=[1576300370])


class ScanTemplateOptions(BaseModel):
    acl: Dict[str, Any] = Field(
        ..., examples=[{'e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8': 'user'}]
    )
    description: Optional[str] = Field(None, examples=['My Scan Template'])
    global_: bool = Field(..., alias='global', examples=[False])
    name: str = Field(..., examples=['My Scan Template'])
    params: Optional[Dict[str, str]] = None


class Search(BaseModel):
    search: str = Field(..., examples=['alive:true and os:windows'])


class Service(BaseModel):
    addresses: Optional[List[str]] = None
    addresses_extra: Optional[List[str]] = None
    agent_name: Optional[str] = Field(None, examples=['LAPTOP-F4P1R6'])
    alive: Optional[bool] = Field(None, examples=[True])
    attributes: Optional[Dict[str, str]] = None
    comments: Optional[str] = Field(None, examples=['File Server'])
    created_at: Optional[int] = Field(None, examples=[1576300370])
    credentials: Optional[Dict[str, str]] = None
    detected_by: Optional[str] = Field(None, examples=['icmp'])
    domains: Optional[List[str]] = None
    first_seen: Optional[int] = Field(None, examples=[1576300370])
    hw: Optional[str] = Field(None, examples=['Dell PowerEdge 2500'])
    id: UUID = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    last_agent_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    last_seen: Optional[int] = Field(None, examples=[1576300370])
    last_task_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    lowest_rtt: Optional[int] = Field(None, examples=[1])
    lowest_ttl: Optional[int] = Field(None, examples=[0])
    mac_vendors: Optional[List[str]] = None
    macs: Optional[List[str]] = None
    names: Optional[List[str]] = None
    newest_mac: Optional[str] = Field(None, examples=['11:22:33:44:55:66'])
    newest_mac_age: Optional[int] = Field(None, examples=[1304035200000000000])
    newest_mac_vendor: Optional[str] = Field(None, examples=['Intel Corporate'])
    org_name: Optional[str] = Field(None, examples=['Test Labs'])
    organization_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    os: Optional[str] = Field(None, examples=['Ubuntu Linux'])
    os_version: Optional[str] = Field(None, examples=[18.04])
    rtts: Optional[Dict[str, Any]] = None
    service_address: Optional[str] = Field(None, examples=['192.168.0.1'])
    service_asset_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    service_count: Optional[int] = Field(None, examples=[10])
    service_count_arp: Optional[int] = Field(None, examples=[1])
    service_count_icmp: Optional[int] = Field(None, examples=[1])
    service_count_tcp: Optional[int] = Field(None, examples=[7])
    service_count_udp: Optional[int] = Field(None, examples=[1])
    service_created_at: Optional[int] = Field(None, examples=[1576300370])
    service_data: Optional[Dict[str, str]] = None
    service_id: UUID = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    service_link: Optional[str] = Field(None, examples=['http://192.168.0.1:80/'])
    service_port: Optional[str] = Field(None, examples=[80])
    service_ports_products: Optional[List[str]] = None
    service_ports_protocols: Optional[List[str]] = None
    service_ports_tcp: Optional[List[str]] = None
    service_ports_udp: Optional[List[str]] = None
    service_protocol: Optional[str] = Field(None, examples=['http tls'])
    service_screenshot_link: Optional[str] = None
    service_summary: Optional[str] = Field(None, examples=['Login Page'])
    service_transport: Optional[str] = Field(None, examples=['tcp'])
    service_updated_at: Optional[int] = Field(None, examples=[1576300370])
    service_vhost: Optional[str] = Field(None, examples=['www'])
    services: Optional[Dict[str, Dict[str, str]]] = None
    site_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    site_name: Optional[str] = Field(None, examples=['Primary'])
    tags: Optional[Dict[str, str]] = None
    type: Optional[str] = Field(None, examples=['Server'])
    updated_at: Optional[int] = Field(None, examples=[1576300370])


class Site(BaseModel):
    created_at: Optional[int] = Field(None, examples=[1576300370])
    description: Optional[str] = Field(None, examples=['Headquarters'])
    excludes: Optional[str] = Field(None, examples=['192.168.0.5'])
    id: UUID = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    name: str = Field(..., examples=['Primary'])
    permanent: Optional[bool] = Field(None, examples=[True])
    scope: Optional[str] = Field(None, examples=['192.168.0.0/24'])
    subnets: Optional[Dict[str, Any]] = None
    updated_at: Optional[int] = Field(None, examples=[1576300370])


class SiteOptions(BaseModel):
    description: Optional[str] = Field(None, examples=['County Office'])
    excludes: Optional[str] = Field(None, examples=['192.168.10.1'])
    name: str = Field(..., examples=['New Site'])
    scope: Optional[str] = Field(None, examples=['192.168.10.0/24'])


class StatusMessage(BaseModel):
    pass


class Task(BaseModel):
    agent_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    client_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    created_at: Optional[int] = Field(None, examples=[1576300370])
    created_by: Optional[EmailStr] = Field(None, examples=['user@example.com'])
    created_by_user_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    cruncher_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    description: Optional[str] = Field(None, examples=['Scan the headquarters hourly'])
    error: Optional[str] = Field(None, examples=['agent unavailable'])
    hidden: Optional[bool] = Field(None, examples=[False])
    id: UUID = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    name: Optional[str] = Field(None, examples=['Hourly Scan'])
    organization_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    params: Optional[Dict[str, str]] = None
    parent_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    recur: Optional[bool] = Field(None, examples=[False])
    recur_frequency: Optional[str] = Field(None, examples=['hour'])
    recur_last: Optional[int] = Field(None, examples=[1576300370])
    recur_last_task_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    recur_next: Optional[int] = Field(None, examples=[1576300370])
    site_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    start_time: Optional[int] = Field(None, examples=[1576300370])
    stats: Optional[Dict[str, Any]] = None
    status: Optional[str] = Field(None, examples=['processed'])
    template_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    type: Optional[str] = Field(None, examples=['scan'])
    updated_at: Optional[int] = Field(None, examples=[1576300370])


class URL(BaseModel):
    id: Optional[str] = Field(None, examples=['https://www.rumble.run/docs/'])


class User(BaseModel):
    client_admin: Optional[bool] = Field(None, examples=[True])
    client_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    created_at: Optional[int] = Field(None, examples=[1576300370])
    email: Optional[str] = Field(None, examples=['jsmith@example.com'])
    first_name: Optional[str] = Field(None, examples=['James'])
    id: UUID = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    invite_token_expiration: Optional[int] = Field(None, examples=[1576300370])
    last_login_at: Optional[int] = Field(None, examples=[1576300370])
    last_login_ip: Optional[str] = Field(None, examples=['192.168.0.1'])
    last_login_ua: Optional[str] = Field(None, examples=['curl/1.0'])
    last_name: Optional[str] = Field(None, examples=['Smith'])
    login_failures: Optional[int] = Field(None, examples=[0])
    org_default_role: Optional[str] = Field(None, examples=['admin'])
    org_roles: Optional[Dict[str, Any]] = None
    reset_token_expiration: Optional[int] = Field(None, examples=[1576300370])
    sso_only: Optional[bool] = Field(None, examples=[False])
    updated_at: Optional[int] = Field(None, examples=[1576300370])


class UserInviteOptions(BaseModel):
    client_admin: Optional[bool] = Field(None, examples=[True])
    email: Optional[str] = Field(None, examples=['jsmith@example.com'])
    first_name: Optional[str] = Field(None, examples=['James'])
    last_name: Optional[str] = Field(None, examples=['Smith'])
    message: Optional[str] = Field(
        None,
        examples=['You have been invited to the Rumble Network Discovery platform'],
    )
    org_default_role: Optional[str] = Field(None, examples=['admin'])
    org_roles: Optional[Dict[str, Any]] = None
    subject: Optional[str] = Field(None, examples=['Welcome to Rumble'])


class UserOptions(BaseModel):
    client_admin: Optional[bool] = Field(None, examples=[True])
    email: Optional[str] = Field(None, examples=['jsmith@example.com'])
    first_name: Optional[str] = Field(None, examples=['James'])
    last_name: Optional[str] = Field(None, examples=['Smith'])
    org_default_role: Optional[str] = Field(None, examples=['admin'])
    org_roles: Optional[Dict[str, Any]] = None


class VMwareCredentialFields(BaseModel):
    insecure: Optional[str] = Field(None, examples=['true'])
    password: str = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    thumbprints: Optional[str] = Field(None, examples=['IP=SHA256:B64HASH'])
    username: str = Field(..., examples=['user'])


class Wireless(BaseModel):
    agent_name: Optional[str] = Field(None, examples=['LAPTOP-F4P1R6'])
    authentication: Optional[str] = Field(None, examples=['wpa2-psk'])
    bssid: Optional[str] = Field(None, examples=['11:22:33:44:55:66'])
    channels: Optional[str] = Field(None, examples=['11, 158+1'])
    created_at: Optional[int] = Field(None, examples=[1576300370])
    data: Optional[Dict[str, str]] = None
    encryption: Optional[str] = Field(None, examples=['aes'])
    essid: Optional[UUID] = Field(None, examples=['Free WiFi'])
    family: Optional[str] = Field(None, examples=[223344])
    id: UUID = Field(..., examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8'])
    interface: Optional[str] = Field(None, examples=['wlan0'])
    last_agent_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    last_seen: Optional[int] = Field(None, examples=[1576300370])
    last_task_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    org_name: Optional[str] = Field(None, examples=['Test Labs'])
    organization_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    signal: Optional[conint(ge=0, le=100)] = Field(None, examples=[99])
    site_id: Optional[UUID] = Field(
        None, examples=['e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8']
    )
    site_name: Optional[str] = Field(None, examples=['Primary'])
    type: Optional[str] = Field(None, examples=['infrastructure'])
    vendor: Optional[str] = Field(None, examples=['Ubiquiti Networks'])


class AccountAgentsGetResponse(RootModel[List[Agent]]):
    root: List[Agent]


class AccountCredentialsGetResponse(RootModel[List[Credential]]):
    root: List[Credential]


class AccountKeysGetResponse(RootModel[List[APIKey]]):
    root: List[APIKey]


class AccountOrgsGetResponse(RootModel[List[Organization]]):
    root: List[Organization]


class AccountSitesGetResponse(RootModel[List[Site]]):
    root: List[Site]


class AccountTasksGetResponse(RootModel[List[Task]]):
    root: List[Task]


class AccountTasksTemplatesGetResponse(RootModel[List[ScanTemplate]]):
    root: List[ScanTemplate]


class AccountUsersGetResponse(RootModel[List[User]]):
    root: List[User]


class OrgAgentsGetResponse(RootModel[List[Agent]]):
    root: List[Agent]


class OrgAssetsGetResponse(RootModel[List[Asset]]):
    root: List[Asset]


class OrgServicesGetResponse(RootModel[List[Service]]):
    root: List[Service]


class OrgSitesGetResponse(RootModel[List[Site]]):
    root: List[Site]


class OrgTasksGetResponse(RootModel[List[Task]]):
    root: List[Task]


class OrgWirelessGetResponse(RootModel[List[Wireless]]):
    root: List[Wireless]


class CredentialFields(
    RootModel[
        Union[
            MiradoreCredentialFields,
            AWSCredentialFields,
            AzureClientSecretCredentialFields,
            AzureUsernamePasswordCredentialFields,
            CrowdstrikeCredentialFields,
            CensysCredentialFields,
            SNMPv2CommunitiesCredentialFields,
            SNMPv3CredentialFields,
            VMwareCredentialFields,
        ]
    ]
):
    root: Union[
        MiradoreCredentialFields,
        AWSCredentialFields,
        AzureClientSecretCredentialFields,
        AzureUsernamePasswordCredentialFields,
        CrowdstrikeCredentialFields,
        CensysCredentialFields,
        SNMPv2CommunitiesCredentialFields,
        SNMPv3CredentialFields,
        VMwareCredentialFields,
    ]


class CredentialOptions(BaseModel):
    acl: Optional[Dict[str, Any]] = Field(
        None,
        examples=[
            {
                'e77602e0-3fb8-4734-aef9-fbc6fdcb0fa8': 'user',
                'e77602e0-3fb8-4734-aef9-fbc6fdcb0fa9': 'none',
            }
        ],
    )
    cidrs: Optional[str] = Field(None, examples=['10.0.0.17/32, 192.168.1.0/24'])
    global_: Optional[bool] = Field(None, alias='global', examples=[False])
    name: Optional[str] = Field(None, examples=['credentials_name'])
    secret: Optional[CredentialFields] = None
    type: Optional[Type1] = Field(None, examples=['miradore_api_key_v1'])
