# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:05:09+00:00

from __future__ import annotations

from typing import List

from pydantic import RootModel

from . import Event


class JsonGetResponse(RootModel[List[Event]]):
    root: List[Event]


class JsonlGetResponse(RootModel[List[Event]]):
    root: List[Event]
