# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:05:09+00:00

from __future__ import annotations

from typing import List

from pydantic import RootModel

from . import Wireless


class JsonGetResponse(RootModel[List[Wireless]]):
    root: List[Wireless]
