# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:05:09+00:00



import argparse
import json
import os
from typing import *
from typing import Optional
from uuid import UUID

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, HTTPBearer
from fastapi import Request

from models import (
    URL,
    AccountAgentsGetResponse,
    AccountCredentialsGetResponse,
    AccountKeysGetResponse,
    AccountOrgsGetResponse,
    AccountSitesGetResponse,
    AccountTasksGetResponse,
    AccountTasksTemplatesGetResponse,
    AccountUsersGetResponse,
    Agent,
    AgentSiteID,
    APIKey,
    APIKeyOptions,
    Asset,
    AssetComments,
    AssetsWithCheckpoint,
    AssetTags,
    AssetTagsWithSearch,
    ComponentVersion,
    Credential,
    CredentialOptions,
    Group,
    GroupMapping,
    GroupPost,
    GroupPut,
    License,
    OrgAgentsGetResponse,
    Organization,
    OrgAssetsGetResponse,
    OrgOptions,
    OrgServicesGetResponse,
    OrgSitesGetResponse,
    OrgTasksGetResponse,
    OrgWirelessGetResponse,
    ScanTemplate,
    ScanTemplateOptions,
    Search,
    Service,
    Site,
    SiteOptions,
    StatusMessage,
    Task,
    User,
    UserInviteOptions,
    UserOptions,
    Wireless,
)
from models.AccountEvents import JsonGetResponse, JsonlGetResponse
from models.ExportOrgAssets import JsonGetResponse
from models.ExportOrgAssets.servicenow import JsonGetResponse
from models.ExportOrgServices import JsonGetResponse
from models.ExportOrgSites import JsonGetResponse
from models.ExportOrgWireless import JsonGetResponse

app = MCPProxy(
    contact={'email': 'support@runzero.com'},
    description='<p><b><i>Rumble Network Discovery is now runZero. <a href="https://www.runzero.com/blog/introducing-runzero/">Read the announcement</a></i></b>.</p> <p>This API is frozen and no longer being updated as of version 2.15.0.</p> <p>See our latest API documentation at <a href="https://app.swaggerhub.com/apis-docs/runZero/runZero">swaggerhub.com/apis-docs/runZero/runZero</a>.</p>\n',
    license={'name': 'Commercial', 'url': 'https://www.runzero.com/legal/terms'},
    title='Rumble API (deprecated)',
    version='2.15.0',
    servers=[
        {'description': 'Rumble Console', 'url': 'https://console.rumble.run/api/v1.0'}
    ],
)


@app.get(
    '/account/agents',
    tags=['agent_management', 'account_organizations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_account_agents(search: Optional[str] = None):
    """
    Get all agents across all organizations
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/account/credentials',
    tags=['account_credentials_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_account_credentials(search: Optional[str] = None):
    """
    Get all account credentials
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/account/credentials',
    tags=['account_credentials_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_account_credential(body: CredentialOptions):
    """
    Create a new credential
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/account/credentials/{credential_id}',
    tags=['account_credentials_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def remove_account_credential(credential_id: UUID):
    """
    Remove this credential
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/account/credentials/{credential_id}',
    tags=['account_credentials_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_account_credential(credential_id: UUID):
    """
    Get credential details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/account/events.json',
    tags=['event_logging_export'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_events_j_s_o_n(search: Optional[str] = None, fields: Optional[str] = None):
    """
    System event log as JSON
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/account/events.jsonl',
    tags=['event_logging_export'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_events_j_s_o_n_l(search: Optional[str] = None, fields: Optional[str] = None):
    """
    System event log as JSON line-delimited
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/account/groups',
    tags=[
        'account_credentials_management',
        'account_groups_management',
        'account_keys_management',
        'account_organizations_management',
        'account_sites_management',
        'account_group_mappings_management',
        'account_group_mapping_retrieval',
        'account_tasks_management',
        'account_scan_template_management',
        'account_user_management',
        'account_user_security_management',
        'asset_inventory_exporting',
        'service_inventory_exporting',
        'site_inventory_exporting',
        'site_data_exporting',
        'wireless_inventory_exporting',
        'organization_details_management',
        'agent_management',
        'asset_management',
        'api_key_management',
        'service_management',
        'site_management',
        'scan_management',
        'wireless_lan_management',
        'version_retrieval',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_account_groups():
    """
    Get all groups
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/account/groups',
    tags=['account_groups_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_account_group(body: GroupPost):
    """
    Create a new group
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/account/groups',
    tags=['account_groups_management', 'account_group_mappings_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def update_account_group(body: GroupPut):
    """
    Update an existing group
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/account/groups/{group_id}',
    tags=['account_groups_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def remove_account_group(group_id: UUID):
    """
    Remove this group
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/account/groups/{group_id}',
    tags=['account_groups_management', 'account_group_mapping_retrieval'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_account_group(group_id: UUID):
    """
    Get group details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/account/keys',
    tags=['account_keys_management', 'api_key_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_account_keys():
    """
    Get all active API keys
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/account/keys',
    tags=['account_keys_management', 'api_key_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_account_key(body: APIKeyOptions):
    """
    Create a new key
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/account/keys/{key_id}',
    tags=['account_keys_management', 'api_key_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def remove_account_key(key_id: UUID):
    """
    Remove this key
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/account/keys/{key_id}',
    tags=['account_keys_management', 'api_key_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_account_key(key_id: UUID):
    """
    Get key details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/account/keys/{key_id}/rotate',
    tags=['account_keys_management', 'api_key_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def rotate_account_key(key_id: UUID):
    """
    Rotates the key secret
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/account/license',
    tags=['account_organizations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_account_license():
    """
    Get license details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/account/orgs',
    tags=['account_organizations_management', 'organization_details_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_account_organizations(search: Optional[str] = None):
    """
    Get all organization details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/account/orgs',
    tags=['account_organizations_management', 'organization_details_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_account_organization(body: OrgOptions):
    """
    Create a new organization
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/account/orgs/{org_id}',
    tags=['account_organizations_management', 'organization_details_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def remove_account_organization(org_id: UUID):
    """
    Remove this organization
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/account/orgs/{org_id}',
    tags=['account_organizations_management', 'organization_details_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_account_organization(org_id: UUID):
    """
    Get organization details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/account/orgs/{org_id}',
    tags=['account_organizations_management', 'organization_details_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def update_account_organization(org_id: UUID, body: OrgOptions = ...):
    """
    Update organization details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/account/orgs/{org_id}/exportToken',
    tags=['account_organizations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def delete_account_organization_export_token(org_id: UUID):
    """
    Removes the export token from the specified organization
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/account/orgs/{org_id}/exportToken/rotate',
    tags=[
        'account_organizations_management',
        'organization_details_management',
        'account_credentials_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def rotate_account_organization_export_token(org_id: UUID):
    """
    Rotates the organization export token and returns the updated organization
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/account/sites',
    tags=['account_sites_management', 'account_organizations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_account_sites(search: Optional[str] = None):
    """
    Get all sites details across all organizations
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/account/sso/groups',
    tags=['account_group_mappings_management', 'account_group_mapping_retrieval'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_account_group_mappings():
    """
    Get all SSO group mappings
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/account/sso/groups',
    tags=['account_group_mappings_management', 'account_groups_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_account_group_mapping(body: GroupMapping):
    """
    Create a new SSO group mapping
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/account/sso/groups',
    tags=['account_group_mappings_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def update_account_group_mapping(body: GroupMapping):
    """
    Update an existing SSO group mapping
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/account/sso/groups/{group_mapping_id}',
    tags=['account_group_mappings_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def remove_account_group_mapping(group_mapping_id: UUID):
    """
    Remove this SSO group mapping
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/account/sso/groups/{group_mapping_id}',
    tags=['account_group_mappings_management', 'account_group_mapping_retrieval'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_account_group_mapping(group_mapping_id: UUID):
    """
    Get SSO group mapping details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/account/tasks',
    tags=['account_tasks_management', 'account_organizations_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_account_tasks(search: Optional[str] = None):
    """
    Get all task details across all organizations (up to 1000)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/account/tasks/templates',
    tags=['account_scan_template_management', 'scan_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_account_scan_templates(search: Optional[str] = None):
    """
    Get all scan templates across all organizations (up to 1000)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/account/tasks/templates',
    tags=['account_scan_template_management', 'scan_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_account_scan_template(body: ScanTemplateOptions):
    """
    Create a new scan template
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/account/tasks/templates',
    tags=['account_scan_template_management', 'scan_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def update_account_scan_template(body: ScanTemplate):
    """
    Update scan template
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/account/tasks/templates/{scan_template_id}',
    tags=['account_scan_template_management', 'scan_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def remove_account_scan_template(scan_template_id: UUID):
    """
    Remove scan template
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/account/tasks/templates/{scan_template_id}',
    tags=['account_scan_template_management', 'scan_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_account_scan_template(scan_template_id: UUID):
    """
    Get scan template details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/account/users',
    tags=['account_user_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_account_users():
    """
    Get all users
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/account/users',
    tags=['account_user_management', 'account_credentials_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_account_user(body: UserOptions):
    """
    Create a new user account
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/account/users/invite',
    tags=['account_user_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_account_user_invite(body: UserInviteOptions):
    """
    Create a new user account and send an email invite
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/account/users/{user_id}',
    tags=['account_user_management', 'account_credentials_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def remove_account_user(user_id: UUID):
    """
    Remove this user
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/account/users/{user_id}',
    tags=['account_user_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_account_user(user_id: UUID):
    """
    Get user details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/account/users/{user_id}',
    tags=['account_user_management', 'account_credentials_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def update_account_user(user_id: UUID, body: UserOptions = ...):
    """
    Update a user's details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/account/users/{user_id}/resetLockout',
    tags=['account_user_security_management', 'account_user_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def reset_account_user_lockout(user_id: UUID):
    """
    Resets the user's lockout status
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/account/users/{user_id}/resetMFA',
    tags=['account_user_security_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def reset_account_user_m_f_a(user_id: UUID):
    """
    Resets the user's MFA tokens
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/account/users/{user_id}/resetPassword',
    tags=['account_user_security_management', 'account_user_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def reset_account_user_password(user_id: UUID):
    """
    Sends the user a password reset email
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/export/org/assets.cisco.csv',
    tags=['asset_inventory_exporting', 'service_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_assets_cisco_c_s_v(search: Optional[str] = None):
    """
    Cisco serial number and model name export for Cisco Smart Net Total Care Service.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/export/org/assets.csv',
    tags=['asset_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_assets_c_s_v(search: Optional[str] = None):
    """
    Asset inventory as CSV
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/export/org/assets.json',
    tags=['asset_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_assets_j_s_o_n(search: Optional[str] = None, fields: Optional[str] = None):
    """
    Exports the asset inventory
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/export/org/assets.jsonl',
    tags=['asset_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_assets_j_s_o_n_l(search: Optional[str] = None, fields: Optional[str] = None):
    """
    Asset inventory as JSON line-delimited
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/export/org/assets.nmap.xml',
    tags=['asset_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_assets_nmap_x_m_l(search: Optional[str] = None):
    """
    Asset inventory as Nmap-style XML
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/export/org/assets.servicenow.csv',
    tags=['asset_inventory_exporting', 'service_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def snow_export_assets_c_s_v():
    """
    Export an asset inventory as CSV for ServiceNow integration
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/export/org/assets.servicenow.json',
    tags=['asset_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def snow_export_assets_j_s_o_n():
    """
    Exports the asset inventory as JSON
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/export/org/assets/sync/created/assets.json',
    tags=['asset_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def splunk_asset_sync_created_j_s_o_n(
    search: Optional[str] = None,
    fields: Optional[str] = None,
    since: Optional[int] = None,
):
    """
    Exports the asset inventory in a sync-friendly manner using created_at as a checkpoint. Requires the Splunk entitlement.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/export/org/assets/sync/updated/assets.json',
    tags=['asset_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def splunk_asset_sync_updated_j_s_o_n(
    search: Optional[str] = None,
    fields: Optional[str] = None,
    since: Optional[int] = None,
):
    """
    Exports the asset inventory in a sync-friendly manner using updated_at as a checkpoint. Requires the Splunk entitlement.
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/export/org/services.csv',
    tags=['service_inventory_exporting', 'asset_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_services_c_s_v(search: Optional[str] = None):
    """
    Service inventory as CSV
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/export/org/services.json',
    tags=['service_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_services_j_s_o_n(search: Optional[str] = None, fields: Optional[str] = None):
    """
    Service inventory as JSON
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/export/org/services.jsonl',
    tags=['service_inventory_exporting', 'asset_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_services_j_s_o_n_l(
    search: Optional[str] = None, fields: Optional[str] = None
):
    """
    Service inventory as JSON line-delimited
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/export/org/services.servicenow.csv',
    tags=[
        'service_inventory_exporting',
        'asset_inventory_exporting',
        'service_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def snow_export_services_c_s_v():
    """
    Export a service inventory as CSV for ServiceNow integration
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/export/org/sites.csv',
    tags=[
        'site_inventory_exporting',
        'site_data_exporting',
        'account_sites_management',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_sites_c_s_v():
    """
    Site list as CSV
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/export/org/sites.json',
    tags=[
        'account_sites_management',
        'site_data_exporting',
        'site_inventory_exporting',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_sites_j_s_o_n(search: Optional[str] = None, fields: Optional[str] = None):
    """
    Export all sites
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/export/org/sites.jsonl',
    tags=['account_sites_management', 'site_data_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_sites_j_s_o_n_l(search: Optional[str] = None, fields: Optional[str] = None):
    """
    Site list as JSON line-delimited
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/export/org/wireless.csv',
    tags=['asset_inventory_exporting', 'wireless_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_wireless_c_s_v(search: Optional[str] = None):
    """
    Wireless inventory as CSV
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/export/org/wireless.json',
    tags=['wireless_inventory_exporting', 'asset_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_wireless_j_s_o_n(search: Optional[str] = None, fields: Optional[str] = None):
    """
    Wireless inventory as JSON
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/export/org/wireless.jsonl',
    tags=['wireless_inventory_exporting', 'asset_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_wireless_j_s_o_n_l(
    search: Optional[str] = None, fields: Optional[str] = None
):
    """
    Wireless inventory as JSON line-delimited
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org',
    tags=['account_organizations_management', 'organization_details_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_organization():
    """
    Get organization details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/org',
    tags=['account_organizations_management', 'organization_details_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def update_organization(body: OrgOptions):
    """
    Update organization details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/agents',
    tags=['agent_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_agents():
    """
    Get all agents
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/org/agents/{agent_id}',
    tags=['agent_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def remove_agent(agent_id: UUID):
    """
    Remove and uninstall an agent
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/agents/{agent_id}',
    tags=['agent_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_agent(agent_id: UUID):
    """
    Get details for a single agent
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/org/agents/{agent_id}',
    tags=['site_management', 'agent_management', 'account_sites_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def update_agent_site(agent_id: UUID, body: AgentSiteID = ...):
    """
    Update the site associated with agent
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/org/agents/{agent_id}/update',
    tags=['agent_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def upgrade_agent(agent_id: UUID):
    """
    Force an agent to update and restart
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/assets',
    tags=['asset_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_assets(search: Optional[str] = None):
    """
    Get all assets
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/org/assets/bulk/clearTags',
    tags=['asset_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def clear_bulk_asset_tags(body: Search):
    """
    Clear all tags across multiple assets based on a search query
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/org/assets/bulk/tags',
    tags=['asset_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def update_bulk_asset_tags(body: AssetTagsWithSearch):
    """
    Update tags across multiple assets based on a search query
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/assets/top.hw.csv',
    tags=[
        'asset_inventory_exporting',
        'service_inventory_exporting',
        'site_inventory_exporting',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_asset_top_h_w_c_s_v():
    """
    Top asset hardware products as CSV
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/assets/top.os.csv',
    tags=['asset_inventory_exporting', 'service_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_asset_top_o_s_c_s_v():
    """
    Top asset operating systems as CSV
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/assets/top.tags.csv',
    tags=['asset_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_asset_top_tags_c_s_v():
    """
    Top asset tags as CSV
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/assets/top.types.csv',
    tags=[
        'asset_inventory_exporting',
        'service_inventory_exporting',
        'site_data_exporting',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_asset_top_types_c_s_v():
    """
    Top asset types as CSV
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/org/assets/{asset_id}',
    tags=['asset_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def remove_asset(asset_id: UUID):
    """
    Remove an asset
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/assets/{asset_id}',
    tags=['asset_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_asset(asset_id: UUID):
    """
    Get asset details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/org/assets/{asset_id}/comments',
    tags=['asset_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def update_asset_comments(asset_id: UUID, body: AssetComments = ...):
    """
    Update asset comments
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/org/assets/{asset_id}/tags',
    tags=['asset_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def update_asset_tags(asset_id: UUID, body: AssetTags = ...):
    """
    Update asset tags
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/org/key',
    tags=['account_keys_management', 'api_key_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def remove_key():
    """
    Remove the current API key
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/key',
    tags=['account_keys_management', 'api_key_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_key():
    """
    Get API key details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/org/key/rotate',
    tags=['account_keys_management', 'api_key_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def rotate_key():
    """
    Rotate the API key secret and return the updated key
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/services',
    tags=['service_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_services(search: Optional[str] = None):
    """
    Get all services
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/services/subnet.stats.csv',
    tags=['asset_inventory_exporting', 'site_data_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_subnet_utilization_stats_c_s_v(mask: Optional[str] = None):
    """
    Subnet utilization statistics as as CSV
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/services/top.products.csv',
    tags=['service_inventory_exporting', 'asset_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_services_top_products_c_s_v():
    """
    Top service products as CSV
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/services/top.protocols.csv',
    tags=[
        'service_inventory_exporting',
        'site_data_exporting',
        'asset_inventory_exporting',
    ],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_services_top_protocols_c_s_v():
    """
    Top service protocols as CSV
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/services/top.tcp.csv',
    tags=['service_inventory_exporting', 'asset_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_services_top_t_c_p_c_s_v():
    """
    Top TCP services as CSV
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/services/top.udp.csv',
    tags=['service_inventory_exporting'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def export_services_top_u_d_p_c_s_v():
    """
    Top UDP services as CSV
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/org/services/{service_id}',
    tags=['service_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def remove_service(service_id: UUID):
    """
    Remove a service
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/services/{service_id}',
    tags=['service_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_service(service_id: UUID):
    """
    Get service details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/sites',
    tags=['account_sites_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_sites():
    """
    Get all sites
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/org/sites',
    tags=['account_sites_management', 'site_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_site(body: SiteOptions):
    """
    Create a new site
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/org/sites/{site_id}',
    tags=['account_sites_management', 'site_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def remove_site(site_id: UUID):
    """
    Remove a site and associated assets
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/sites/{site_id}',
    tags=['account_sites_management', 'site_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_site(site_id: UUID):
    """
    Get site details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/org/sites/{site_id}',
    tags=['account_sites_management', 'site_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def update_site(site_id: UUID, body: SiteOptions = ...):
    """
    Update a site definition
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/org/sites/{site_id}/import',
    tags=['account_sites_management', 'scan_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def import_scan_data(site_id: UUID, request: Request = ...):
    """
    Import a scan data file into a site
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/org/sites/{site_id}/import/nessus',
    tags=['site_management', 'scan_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def import_nessus_scan_data(site_id: UUID, request: Request = ...):
    """
    Import a Nessus scan data file into a site
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/org/sites/{site_id}/scan',
    tags=['account_sites_management', 'scan_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def create_scan(site_id: UUID):
    """
    Create a scan task for a given site
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/tasks',
    tags=['account_tasks_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_tasks(status: Optional[str] = None, search: Optional[str] = None):
    """
    Get all tasks (last 1000)
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/tasks/{task_id}',
    tags=['account_tasks_management', 'scan_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_task(task_id: UUID):
    """
    Get task details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/org/tasks/{task_id}',
    tags=['account_tasks_management', 'scan_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def update_task(task_id: UUID, body: Task = ...):
    """
    Update task parameters
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/tasks/{task_id}/changes',
    tags=['account_tasks_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_task_change_report(task_id: UUID):
    """
    Returns a temporary task change report data url
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/tasks/{task_id}/data',
    tags=['account_tasks_management', 'scan_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_task_scan_data(task_id: UUID):
    """
    Returns a temporary task scan data url
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/org/tasks/{task_id}/hide',
    tags=['account_tasks_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def hide_task(task_id: UUID):
    """
    Signal that a completed task should be hidden
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/tasks/{task_id}/log',
    tags=['account_tasks_management', 'scan_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_task_log(task_id: UUID):
    """
    Returns a temporary task log data url
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/org/tasks/{task_id}/stop',
    tags=['account_tasks_management', 'scan_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def stop_task(task_id: UUID):
    """
    Signal that a task should be stopped or canceledThis will also remove recurring and scheduled tasks
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/wireless',
    tags=['wireless_lan_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_wireless_l_a_ns(search: Optional[str] = None):
    """
    Get all wireless LANs
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/org/wireless/{wireless_id}',
    tags=['wireless_lan_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def remove_wireless_l_a_n(wireless_id: UUID):
    """
    Remove a wireless LAN
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/org/wireless/{wireless_id}',
    tags=['wireless_lan_management'],
    security=[
        HTTPBearer(name="None"),
    ],
)
def get_wireless_l_a_n(wireless_id: UUID):
    """
    Get wireless LAN details
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/releases/agent/version', tags=['agent_management', 'version_retrieval'])
def get_latest_agent_version():
    """
    Returns latest agent version
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/releases/platform/version', tags=['version_retrieval'])
def get_latest_platform_version():
    """
    Returns latest platform version
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/releases/scanner/version', tags=['version_retrieval'])
def get_latest_scanner_version():
    """
    Returns latest scanner version
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
